version: '2.4'

services:

  redis:  #用作快取與Session
    image: redis:latest #有現成的image就直接使用不用build
    ports:
      - "6379:6379" #要對應的port不然接不到
  
  db:
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=eric"
      - "MYSQL_PASSWORD=1234"
    volumes:
      - "dbdata:/var/lib/mysql"
    ports:
      - "3306:3306"
volumes:
    dbdata: #這裡可以留空,Docker會在本機設置一個volume