version: '2.4'

services:
   web:
#    build:
#      context: .
#      dockerfile: web.docker 
    image: nginx:latest
    volumes:
      - "/d/Myspace/Dockzone/php/vhost.conf:/etc/nginx/conf.d/default.conf"
    container_name: "web-server"
    ports:
      - "80:80" #要對應的port不然接不到
    depends_on:
      - app
    networks:
      - innerlink
   app:
    image: php:7.2.18-fpm
    container_name: "web-app"
    volumes:
      - "/d/Myspace/Dockzone/php/public:/var/www/html"
    networks:
      - innerlink
networks:
  innerlink:
    driver: bridge
